version: 2

models:
  - name: fact_sales
    description: "Fact table for sales transactions"
    columns:
      - name: order_id
        tests:
          - not_null
      - name: date_key
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_key

  - name: dim_customer
    description: "Customer dimension"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: dim_product
    description: "Product dimension"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: fact_reviews
    description: "Fact table for order reviews"
    columns:
      - name: review_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
